### ISSUE TITLE
Update node version in gh-pages.yml workflow file

### ISSUE THREAD

**Issue by Pepper-Wood** [dgarcia360/openapi-boilerplate#8]
Thank you for putting this templated repo together! I found it extremely useful when utilizing it in my own project.

## Bug Summary
A recent build following the workflow file `gh-pages.yml` resulted in the below error:
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'react-is'
```

<details>
<summary>Click for full error message</summary>

```
Run npm ci
added 414 packages in 4.487s

> daeclipse-openapi-spec@0.0.4 build /home/runner/work/daeclipse/daeclipse
> swagger-cli bundle spec/openapi.yaml --outfile _build/api/openapi.yaml --type yaml

Created _build/api/openapi.yaml from spec/openapi.yaml

> daeclipse-openapi-spec@0.0.4 html /home/runner/work/daeclipse/daeclipse
> npm run build && redoc-cli bundle _build/api/openapi.yaml  --output _build/api/index.html --options.onlyRequiredInSamples


> daeclipse-openapi-spec@0.0.4 build /home/runner/work/daeclipse/daeclipse
> swagger-cli bundle spec/openapi.yaml --outfile _build/api/openapi.yaml --type yaml

Created _build/api/openapi.yaml from spec/openapi.yaml
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'react-is'
Require stack:
- /home/runner/work/daeclipse/daeclipse/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js
- /home/runner/work/daeclipse/daeclipse/node_modules/redoc-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/daeclipse/daeclipse/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js:1:145)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/daeclipse/daeclipse/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js',
    '/home/runner/work/daeclipse/daeclipse/node_modules/redoc-cli/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! daeclipse-openapi-spec@0.0.4 html: `npm run build && redoc-cli bundle _build/api/openapi.yaml  --output _build/api/index.html --options.onlyRequiredInSamples`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the daeclipse-openapi-spec@0.0.4 html script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-07T15_20_03_874Z-debug.log
Error: Process completed with exit code 1.
```

</details>

Link to build: https://github.com/Pepper-Wood/daeclipse/runs/3269822656

## Proposed Solution

Thanks to this comment - https://github.com/nodejs/help/issues/1846#issuecomment-480563345 - a working fix was to update the node version that's listed in the `gh-pages.yml` workflow file.

Link to my code change: https://github.com/Pepper-Wood/daeclipse/commit/5dac86fadd552802021c6d600a65c2c0e48cb768

Following the `diff` here should be able to future-proof if any others run into the same issue with attempting to deploy.

**Comment by dgarcia360** [comment]
@Pepper-Wood First off, sorry for the +6 month delay. Many thanks for providing a fix!

I'm glad you find the extension useful. I recently had the time to upgrade the dependencies of this project to the latest version https://github.com/dgarcia360/openapi-boilerplate/commit/f4b2aa5635e2eab15a99d4888168c867d27257d8

Please do not hesitate to let me know any other improvements you applied to ``daeclipse``!
